id = "template" # Must be same as the folder name. Can only include = lowercase letters a-z, numbers 0-9, underscores _.
description = "This is template of a template" # Description of this template
version = 0 # Every time you change this template, increase this number