id = "template" # Must be same as the folder name. Can only include = lowercase letters a-z, numbers 0-9, underscores _.
description = "This is template of a library" # Description of this library
version = 0 # Every time you change this library, increase this number

[import]
javascript = ["index.js"]
css = ["style.css"]