description = "This is template of a library" # Description of this library
version = 0 # Every time you change this library, increase this number

[import]
priority = 0 # In which order files will be imported. Check https://github.com/pg255/pix128/blob/main/documentation/documentation.md#libraries
javascript = ["index.js"] # All of these files will be included in index.html file
css = ["style.css"] # All of these files will be included in index.html file