id = "template" # Must be same as the folder name. Can only include = lowercase letters a-z, numbers 0-9, underscores _.
description = "This is template of an engine" # Description of this engine
version = 0 # Every time you change this engine, increase this number

[import]
javascript = ["index.js"]
css = ["style.css"]